version: '3'
services:
  system_load:
    build: .
    command: ./main
    ports:
      - "8080:8080"
    networks:
      - shared_network

  network_load:
    build: .
    command: ./network_test
    ports:
      - "8081:8081"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
