apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-sidecar-config
data:
  objstore.yml: |
    type: S3
    config:
      bucket: "thanos"
      endpoint: "minio:9000"
      access_key: "minioaccesskey"
      secret_key: "miniosecretkey"
      insecure: true
