apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-sidecar
  template:
    metadata:
      labels:
        app: thanos-sidecar
    spec:
      containers:
      - name: thanos-sidecar
        image: thanosio/thanos:v0.25.0
        args:
          - "sidecar"
          - "--prometheus.url=http://prometheus:9090"
          - "--tsdb.path=/prometheus"
          - "--objstore.config-file=/etc/thanos/objstore.yml"
        ports:
        - containerPort: 10902
        volumeMounts:
        - name: sidecar-config
          mountPath: /etc/thanos/objstore.yml
          subPath: objstore.yml
      volumes:
      - name: sidecar-config
        configMap:
          name: thanos-sidecar-config
